import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Rodrigo Méndez - Fotografía</title>
      <meta
        name="description"
        content="Rodrigo Méndez - Fotografía en Gaudalajara"
      />

      <meta property="fb:app_id" content="" />
      <meta property="og:url" content="https://rodrigomendez.art" />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="Rodrigo Méndez - Fotografía" />
      <meta property="og:image" content="" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:description" content="" />
      <meta property="og:site_name" content="Rodrigo Méndez" />
      <meta property="og:locale" content="es_MX" />
      <meta property="og:locale:alternate" content="es_MX" />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="" />
      <meta name="twitter:url" content="https://rodrigomendez.art" />
      <meta name="twitter:title" content="Rodrigo Méndez - Fotografía" />
      <meta name="twitter:description" content="" />
      <meta name="twitter:image" content="" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
